# Generated by Django 4.2.4 on 2023-08-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('bio', models.CharField(max_length=100)),
                ('can_hire', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('timezone', models.CharField(max_length=20)),
            ],
        ),
    ]
